ttsx/carts/urls.py
from django.urls import path

from carts.views import *

urlpatterns = [
    path('index/', index,name='index'),
    path('add_cart/', add_cart, name='add_cart'),
    path('place_order/', place_order,name='place_order'),
    path('change_cart/',change_cart,name='change_cart')


]

ttsx/goods/urls.py
from django.urls import path

from goods.views import *

urlpatterns = [
    path('goodlist/', goodlist, name='goodlist'),
    path('detail/', detail, name='detail'),
]

ttsx/order/urls.py
from django.urls import path

from order.views import *

urlpatterns = [
    path('index/', index, name='index'),
    path('add_order/',add_order,name='add_order'),
    path('new_order/',new_order,name='new_order')

]

ttsx/ttsx/urls.py
from django.contrib import admin

from django.urls import path, include

from django.contrib.staticfiles.urls import static

from ttsx.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user1/',include(('user.urls', 'user'))),
    path('carts/',include(('carts.urls', 'carts'),namespace='carts')),
    path('goods/',include(('goods.urls', 'goods'),namespace='goods')),
    path('order/',include(('order.urls', 'order'),namespace='order')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

ttsx/carts/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

ttsx/goods/models.py
from django.db import models

# Create your models here.
class GoodsCategory(models.Model):
    """
    Goods类别
    """
    CATEGORY_TYPE = (
        (1, '新鲜水果'),
        (2, '海鲜水产'),
        (3, '猪牛羊肉'),
        (4, '禽类蛋品'),
        (5, '新鲜蔬菜'),
        (6, '速冻食品'),
    )
    category_type = models.IntegerField(choices=CATEGORY_TYPE, verbose_name='类目级别')
    category_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')

    class Meta:
        db_table = 'f_goods_category'


class Goods(models.Model):
    """
    商品
    """
    category = models.ForeignKey(GoodsCategory, verbose_name='商品类目', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='商品名')
    goods_sn = models.CharField(max_length=50, default='', verbose_name='商品唯一货号')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    sold_nums = models.IntegerField(default=0, verbose_name='销售量')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    goods_nums = models.IntegerField(default=0, verbose_name='商品库存')
    market_price = models.FloatField(default=0, verbose_name='市场价格')
    shop_price = models.FloatField(default=0, verbose_name='本店价格')
    goods_brief = models.CharField(max_length=500, verbose_name='商品简短描述')
    goods_desc = models.TextField(null=True)
    ship_free = models.BooleanField(default=True, verbose_name='是否承担运费')
    goods_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')
    is_new = models.BooleanField(default=False, verbose_name='是否新品')
    is_hot = models.BooleanField(default=False, verbose_name='是否热销')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods'


class liulan(models.Model):
    goodsid = models.ForeignKey(Goods, verbose_name='商品id', on_delete=models.CASCADE)

    class Meta:
        db_table = 'f_liulan'

ttsx/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from carts.models import ShoppingCart
from goods.models import Goods
from order.models import UserAddress
from ttsx.settings import DATABASES
from utils.functions import session_login


# @session_login
# 购物车首页                                       try：不报错执行  exce：报错执行
def index(request):
    if request.method == 'GET':
        try:
            #取得到user说明登陆了，取不到会报错
            user = request.session['user_id']
            # 取到购物车表里用户的购物车数据
            cart = ShoppingCart.objects.filter(user_id=user).all()
            # 返回，传去一个对象
            return render(request, 'cart.html', {'cart': cart})
        except:
                # 没登陆   给一个空字典
                f_goods={}
                # 取到session里保存的商品数据 实际就是商品的 id 和 数量
                goods = request.session.get('goods')

                try:
                    # 如果session里没有商品数据，那么下面的循环语句就会报不可迭代错误，
                    for i in goods:
                        # print(i)    goods={商品id：商品数量, 。。。。}
                        # 遍历取到goods的键，goods[i]取到值， Goods.objects.filter(id=i)从商品表里拿到跟id一样的对象
                        # 往f_goods空字典里添加数据， 以对象做键，goods[i]做值， 字典键不存在添加，存在修改值
                        f_goods[Goods.objects.filter(id=i)]=goods[i]
                except:
                    pass
        return render(request, 'cart.html',{'f_goods': f_goods})

    if request.method == 'POST':
        id = request.POST.get('goods_id')
        try:
            user = request.session['user_id']
            print(id,user)
            # 删除
            ShoppingCart.objects.filter(goods_id=id,user_id=user).delete()
            return JsonResponse({'code': 200})
        except:
            goods = request.session.get('goods')
            # request.session['goods_id'] = goods
            # print(request.session['goods_id'])
            goods.pop(id)
            request.session['goods_id'] = goods
            return JsonResponse({'code': 200})
            # print(request.session['goods_id'])



def add_cart(request):
    if request.method == 'POST':
        #获取到前端ajax传过来的两个值  id：商品id   num：商品数量
        id = request.POST.get('goods_id')
        num = int(request.POST.get('goods_num'))
        # print(id)
        # print(num)
        # 查看是否登录，登录购物车加数据库，没登录session
        try:
            # 直接获取session 登录id， 如果获取不到，报错执行except，获取的到，代表登陆，执行try
            user =request.session['user_id']
            print(user)
            # TRUNCATE TABLE f_shopping_cart  表自增空从1开始的sql语句
            cart = ShoppingCart.objects.filter(goods_id=id).first()
            if cart:
                ShoppingCart.objects.filter(user_id=user,goods_id=id).update(nums=num)
            if not cart:
                ShoppingCart.objects.create(nums=num, goods_id=id, user_id=user)
            #状态码返回，前端接受状态码来进行下一步操作
            return JsonResponse({'code': 200})
        except:
            # 没登陆
            try:
                # 参数 goods 获取到商品存的session值，获取不到报错执行except，其次往下执行
                goods =dict(request.session.get('goods'))
                # 判定前端传过来的商品id 存不存在商品的session值里，存在就修改数量， 商品的session值我们存的是一个字典{商品id：商品数量}
                # 存在：
                if id in goods:
                    goods[id] += num
                    request.session['goods'] = goods

                # 不存在：  不存在就添加一个字典，不会覆盖之前的，  update  。然后重新定义session缓存
                else:
                    goods.update({id:num})
                    request.session['goods'] = goods
                return JsonResponse({'code': 400})


            except:
                #  获取不到session  往session缓存里保存商品数据
                request.session['goods'] = {id:num}
                return JsonResponse({'code': 400})


def change_cart(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        num = int(request.POST.get('num'))
        # print(type(id),id,type(num),num)
        # print(request.session['goods'])
        # 查看是否登录，登录购物车加数据库，没登录session
        try:
            # 直接获取session 登录id， 如果获取不到，报错执行except，获取的到，代表登陆，执行try
            user = request.session['user_id']
            ShoppingCart.objects.filter(goods_id=id,user_id=user).update(nums=num)
            return JsonResponse({'code': 200})
        except:
            # 没登陆
            goods = request.session.get('goods')
            # print(goods)
            goods[id]=num
            # print(goods)
            request.session['goods'] = goods
            return  JsonResponse({'code': 200})

def place_order(request):
    if request.method == 'GET':
        user_address = UserAddress.objects.all()
        user = request.session['user_id']
        goods = ShoppingCart.objects.filter(user_id=user).all()
        return render(request, 'place_order.html',{'add':user_address,'goods':goods})

ttsx/templates/base_main.html
{% extends 'base.html' %}

{% block title %}天天生鲜{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
     <script type="text/javascript" src="{% static 'js/jquery-ui.min.js'%}"></script>
     <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block aa %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if user %}
				<div class="login_info fl">
					欢迎您：<em>{{ user }}</em>
				</div>
                <div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else %}
				<div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:login' %}">登录</a>
                </div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:UserCenter' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:index' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:add_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% endblock %}


    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'carts:index' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'user:index' %}">首页</a></li>
				<li class="interval">|</li>
                <li><a href="{% url 'goods:goodlist' %}">商品列表</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

    {% for k,vlaue in goodstype.items %}
	<div class="list_model">
		<div class="list_title clearfix">
{#   {{ forloop.counter }} 自增id    #}
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ vlaue.2.get_category_type_display }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for i in vlaue.1 %}
				<a href="#">{{ i.name|slice:'5' }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:goodlist' %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl">
                <img src="/{{ vlaue.2.category_front_image }}"></div>

                <ul class="goods_list fl">
                    {% for good in vlaue.0 %}
                    <li>
                        <h4><a href="#">{{ good.name }}</a></h4>
                        <a href="{% url 'goods:detail' %}?id={{ good.id }}"><img src="/{{ good.goods_front_image }}"></a>
                        <div class="prize">¥ {{ good.shop_price }}</div>
                    </li>
                    {% endfor %}
                </ul>
        </div>
    </div>
    {% endfor %}
















{#	<script type="text/javascript" src="js/slideshow.js"></script>#}
{#	<script type="text/javascript">#}
{#		BCSlideshow('focuspic');#}
{#		var oFruit = document.getElementById('fruit_more');#}
{#		var oShownum = document.getElementById('show_count');#}
{##}
{#		var hasorder = localStorage.getItem('order_finish');#}
{##}
{#		if(hasorder)#}
{#		{#}
{#			oShownum.innerHTML = '2';#}
{#		}#}
{##}
{#		oFruit.onclick = function(){#}
{#			window.location.href = 'list.html';#}
{#		}#}
{#	</script>#}
{% endblock %}

{% block bb %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


     {% endblock %}

ttsx/templates/index.html
{% extends 'base_main.html' %}

ttsx/templates/list.html
{% extends 'base_main.html' %}

{% block title %}
    商品列表
{% endblock %}


    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'carts:index' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
                {% for i in new_user %}
				<ul>
					<li>
						<a href="{% url 'goods:detail' %}?id={{ i.id }}"><img src="/{{ i.goods_front_image }}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ i.id }}">{{ i.name }}</a></h4>
						<div class="prize">￥{{ i.shop_price }}</div>
					</li>
				</ul>
                {% endfor %}
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>


			<ul class="goods_type_list clearfix">

                {% for i in users %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ i.id }}"><img src="/{{ i.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' %}?page={{ i.id }}">{{ i.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.shop_price }}</span>
						<span class="unit">{{ i.shop_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if users.has_previous%}
					<a href="{% url 'goods:goodlist' %}?page={{ users.previous_page_number }}">上一页</a>
                {% endif %}


                {% for i in users.paginator.page_range %}
                    <a href="{% url 'goods:goodlist' %}?page={{ i }}"  class="active">{{ i }}</a>
                {% endfor %}


				 {% if users.has_next %}
					    <a href="{% url 'goods:goodlist' %}?page={{ users.next_page_number }}">下一页</a>
                    {% endif %}

			</div>
		</div>
	</div>
    {% endblock %}

ttsx/templates/login.html
{% extends 'index.html' %}

{% block title %}
    登录
{% endblock %}

{% block aa %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if user %}
				<div class="login_info fl">
					欢迎您：<em>{{ user }}</em>
				</div>
                <div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else %}
				<div class="login_btn fl">
                    <span>|</span>
					<a href="{% url 'user:login' %}">登录</a>
                </div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:UserCenter' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:index' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:add_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}





{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'user:index' %}" class="login_logo"><img src="/static/images/logo.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					{% block a%}
                    <h1>用户登录</h1>
                     {% endblock %}
                        {% block b %}
					<a href="{% url 'user:register' %}">立即注册</a>
                        {% endblock %}
				</div>
				<div class="form_input">

                    {% block c %}
					<form action="" method="post">

						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">{{ errors.username }}</div>

						<input type="password" name="password" class="pass_input" placeholder="请输入密码">

						<div class="pwd_error">{{ errors.password }}{{ pwd_error }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                    {% endblock %}

				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
{% endblock %}

{% block bb %}
{% endblock %}

ttsx/templates/user_center_info.html
{% extends 'base_main.html' %}

{% block title %}用户中心{% endblock %}




{% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:UserCenter' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'order:add_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:index' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>18210569700</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for i in gs %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ i.goodsid.id }}"><img src="/{{ i.goodsid.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ i.goodsid.id }}">{{ i.goodsid.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.goodsid.shop_price }}</span>
						<span class="unit">{{ i.goodsid.shop_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}


			</ul>
		</div>
		</div>
	</div>

{% endblock %}

ttsx/templates/user_center_order.html
{% extends 'base_main.html' %}

{% block title %}
    我的订单
{% endblock %}

{% block body %}
    <div class="search_bar clearfix">
        <a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:UserCenter' %}"> · 个人信息</a></li>
                <li><a href="{% url 'order:add_order' %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'order:index' %}">· 收货地址</a></li>
            </ul>
        </div>


        <div class="right_content clearfix">


            <h3 class="common_title2">全部订单</h3>
            {% for i in orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ i.add_time }}</li>
                    <li class="col02">订单号：{{ i.order_sn }}</li>
                    <li class="col02 stress">未支付</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for v in i.A %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src='/{{ v.goods.goods_front_image }}'></li>
                                    <li class="col02">{{ v.goods.name }}<em>{{ v.goods.shop_price }}元/500g</em></li>
                                    <li class="col03">{{ v.goods_nums }}</li>
                                    <li class="col04">{{ v.goods.shop_price }} 元</li>
                                </ul>
                            {% endfor %}

                        </td>
                        <td width="15%">{{ i.order_mount }}元</td>
                        <td width="15%">待付款</td>
                        <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                    </tr>


                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                {% if users.has_previous %}
                    <a href="{% url 'goods:index' %}?page={{ users.previous_page_number }}">上一页</a>
                {% endif %}

                {% for i in users.paginator.page_range %}
                    <a href="{% url 'goods:index' %}?page={{ i }}" class="active">{{ i }}</a>
                {% endfor %}

                {% if users.has_next %}
                    <a href="{% url 'goods:index' %}?page={{ users.next_page_number }}">下一页</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

ttsx/templates/user_center_site.html
{% extends 'base_main.html' %}


{% block title %}
    收获地址
{% endblock %}



    {% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'user:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:UserCenter' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:add_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:index' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                       {% for i in add %}
						<dd>{{ i.address}}({{ i.user }}收){{ i.signer_mobile }}</dd>
                        {% endfor %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">


					<form action="" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="filename">{{ errors.filename}}
						</div>

						<div class="form_group form_group2">
							<label>详细地址：</label>
                            <input type="text" class="site_area" name="address">{{ errors.address }}
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zipcode">
						</div>

						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="number">{{ errors.number }}
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>



				</div>
		</div>
	</div>
    {% endblock %}